### ISSUE TITLE
Implement author component on article page

### ISSUE THREAD

**Issue by mhrechkin** [BinaryStudioAcademy/bsa-2023-writorium#53]
**User story:**
As a reader visiting the article page, I want to view essential information about the author prominently displayed in an author component. This will help me quickly understand the author’s credentials and popularity, enhancing my overall reading experience.

**Acceptance criteria:**
- [ ]  The author’s avatar should be visible in the author component, accurately representing the author’s profile picture.
- [ ]  The author’s full name, follower count, and star rating should be displayed accurately in the author component.
- [ ]  The article’s publication in the format Month D, Yr, estimated reading time and genre of article should be visible and reflect accurate information about the article.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/83463107/639f5257-5bc9-4771-8f68-d4b75b7e6dc0)

**Comment by lera777** [comment]
**Description**
The size of the author's avatar does not match the size of the avatar by design.

**Steps to reproduce:**
1 Open website article page https://writorium-development-1c771c6e3c1a.herokuapp.com/articles/article.
2 Pay attention to the size of the author's avatar does not match the size of the avatar by design.

**Actual result:**
The size of the author's avatar does not match the size of the avatar by design.

**Expected result:**
The size of the author's avatar matches the size of the avatar by design.
**Additional information:**




![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/36c0e9be-2006-45b5-8c42-029268543c6e)



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/9a6b4f2a-9dbf-4b51-8b2e-1c64cb2d7a5f)






**Environment:**
OS: macOS Catalina 10.15.7
Browser: Google Chrome 116.0.5845.110

**Severity:**
Low

**Priority:**
Low

**Comment by lera777** [comment]
- [x] The article’s publication date should be in the format Month D, Yr (January 29, 2017).

 **Environment:**
OS: macOS Catalina 10.15.7
Browser: Google Chrome 116.0.5845.110

**Severity:**
Low

**Priority:**
Medium
